### PR TITLE
Collect wisdom service’s analytics telemetry

### PR DESCRIPTION
**Pull request by romartin**
## Description
See [AAP-18658](https://issues.redhat.com/browse/AAP-18658)

## Production deployment
- [ ] This code change is ready for production on its own
- [ ] This code change requires the following considerations before going to production:

Thanks!

### CODE REVIEW

**Review by manstis — COMMENTED** [review]
A couple of minor questions; otherwise looking good.

**Review by manstis — DISMISSED** [review]
Seems reasonable enough to me :+1:

**Review by manstis — APPROVED** [review]
LGTM :+1:

**Review by TamiTakamiya — APPROVED** [review]
LGTM. Thanks for all changes!

**Pull request merged**
