### PR TITLE
[DAST] Lightspeed Downstream: CSP: style-src unsafe-inline

### PR DESCRIPTION
**Pull request by hasys**
Jira Issue: <https://issues.redhat.com/browse/AAP-24975>

## Description

Remove all inline CSS and move it to styles.css file to avoid style-src unsafe-inline

### Steps to test
1. Pull down the PR
2. Run wisdom_service
3. No errors about style-src unsafe-inline are present in the DEV console in your browser while using web site.

## Production deployment

- [x] This code change is ready for production on its own

### CODE REVIEW

**Comment by hasys** [comment]
Issue with pip-audit should be fixed by https://github.com/ansible/ansible-ai-connect-service/pull/1128

**Review by manstis — DISMISSED** [review]
LGTM :+1: Thank-you @hasys

**Comment by hasys** [comment]
Hello @manstis,

sorry had to rebase to main due to conflicts. Need your approve again :) 

new pip-audit issue is fixed by https://github.com/ansible/ansible-ai-connect-service/pull/1134

**Review by manstis — APPROVED** [review]
LGTM :+1:

**Pull request merged**
