### PR TITLE
AAP-28822: remove the Chat links from the footers

### PR DESCRIPTION
**Pull request by goneri**

### CODE REVIEW

**Review by manstis — COMMENTED** [review]
I think @TamiTakamiya may have been repurposing these for the Chat Bot. Have you asked?

**Comment by goneri** [comment]
> I think @TamiTakamiya may have been repurposing these for the Chat Bot. Have you asked?

This change is a request from Og.

**Comment by omaciel** [comment]
Screenshot 2024-09-19 at 16 16 10

**Comment by omaciel** [comment]
ack

**Comment by omaciel** [comment]
This is AAP-28822 btw

**Review by omaciel — APPROVED** [review]
/lgtm

**Pull request merged**
