### PR TITLE
remove the BlockUserWithoutSeatAndWCAReadyOrg permission

### PR DESCRIPTION
**Pull request by goneri**
Jira Issue: <https://issues.redhat.com/browse/AAP-26773>

## Description

We don't use this permission since the removal of the seat system.

## Testing

SAAS already ignores this permission.

## Production deployment

- [x] This code change is ready for production on its own
- [ ] This code change requires the following considerations before going to production:

### CODE REVIEW

**Review by manstis — DISMISSED** [review]
LGTM 👍 

Do you plan on creating a PR for VSCode to remove the obsolete exception code mappings?

**Comment by goneri** [comment]
> LGTM 👍
> 
> Do you plan on creating a PR for VSCode to remove the obsolete exception code mappings?

Good point, here we go -> https://github.com/ansible/vscode-ansible/pull/1423

**Comment by manstis** [comment]
@goneri Did you want to include [this](https://github.com/ansible/ansible-ai-connect-service/pull/1185/files#diff-c72485ff66df5689515e88dfd9c0c2ee1d5adc307b753cac57da208363f6f958L22) removal too in your VSCode PR?

**Comment by goneri** [comment]
Converted to Draft until the test-suite is fixed.

**Review by manstis — COMMENTED** [review]
Erm..... this looks familiar :laughing: 

Did I imagine the reverse of this in a parallel universe?

**Comment by goneri** [comment]
> Erm..... this looks familiar 😆
> 
> Did I imagine the reverse of this in a parallel universe?

A multiverse universe where the Seat management system still exists :-).

**Pull request closed without merging**
