### PR TITLE
finish the ansible_wisdom ansible_ai_connect transition

### PR DESCRIPTION
**Pull request by goneri**
Jira Issue: <https://issues.redhat.com/browse/AAP-19331>

Rename the Python package from `ansible_wisdom` to `ansible_ai_connect`.

See: https://github.com/ansible/ansible-ai-connect-service/pull/990
See: https://github.com/ansible/ansible-ai-connect-service/pull/883

- Deploy the branch
- Validate the service runs like before

- [x] This code change is ready for production on its own
- [ ] This code change requires the following considerations before going to production:

### CODE REVIEW

**Comment by goneri** [comment]
Note: I've split this up in two, This one and https://github.com/ansible/ansible-ai-connect-service/pull/1142

**Comment by manstis** [comment]
Can you fix the conflicts first please, @goneri

**Review by manstis — DISMISSED** [review]
LGTM :+1: 

Thankfully it's just a rename :smile:

**Review by manstis — APPROVED** [review]
LGTM :+1:

**Comment by goneri** [comment]
YOLO!

**Pull request merged**
