### PR TITLE
remove pytorch etc

### PR DESCRIPTION
**Pull request by jameswnl**
https://issues.redhat.com/browse/AAP-24568

## Description

Follow up to https://github.com/ansible/ansible-ai-connect-service/pull/1123.

This PR will cut the image size from 903MB to 571MB

### Steps to test
1. PR deployment

## Production deployment

- [x] This code change is ready for production on its own
- [ ] This code change requires the following considerations before going to production:

### CODE REVIEW

**Comment by jameswnl** [comment]
PR Deployment created in namespace wisdom-pr-1156

 Look up the wisdom-service url in the cluster

**Comment by jameswnl** [comment]
PR Deployment created in namespace wisdom-pr-1156

 Look up the wisdom-service url in the cluster

**Comment by jameswnl** [comment]
We can ignore that konflux verify error

**Review by manstis — APPROVED** [review]
LGTM 👍

**Comment by jameswnl** [comment]
PR Deployment created in namespace wisdom-pr-1156

 Look up the wisdom-service url in the cluster

**Pull request merged**
