### PR TITLE
requirements: upgrade to cryptography==43.0.1

### PR DESCRIPTION
**Pull request by goneri**
This to address GHSA-h4gh-qq45-vh27.

### CODE REVIEW

**Review by manstis — COMMENTED** [review]
I think you'll need the [requirements-aarch64.txt](https://github.com/ansible/ansible-ai-connect-service/blob/main/requirements-aarch64.txt) requirements files too.

Does [pyproject.toml](https://github.com/ansible/ansible-ai-connect-service/blob/main/pyproject.toml) need looking at?

**Comment by goneri** [comment]
> I think you'll need the [requirements-aarch64.txt](https://github.com/ansible/ansible-ai-connect-service/blob/main/requirements-aarch64.txt) requirements files too.

Oh, thanks.

> Does [pyproject.toml](https://github.com/ansible/ansible-ai-connect-service/blob/main/pyproject.toml) need looking at?

No, the current versions should still work as expected.

**Comment by goneri** [comment]
> > Does [pyproject.toml](https://github.com/ansible/ansible-ai-connect-service/blob/main/pyproject.toml) need looking at?
> 
> No, the current versions should still work as expected.

Actually, I was wrong and we should not even have a dependency on `cryptography` since we don't use it directly.

**Review by manstis — APPROVED** [review]
LGTM :+1: 

But Snyk would like you to upgrade Django too!

**Comment by goneri** [comment]
> LGTM 👍
> 
> But Snyk would like you to upgrade Django too!

Thanks for the +1. Yes, I saw that. It's coming in a different PR.

**Comment by goneri** [comment]
Follow up here: https://github.com/ansible/ansible-ai-connect-service/pull/1289

**Pull request merged**
