### PR TITLE
Sentiment feedback

### PR DESCRIPTION
**Pull request by TamiTakamiya**
Jira Issue: <https://issues.redhat.com/browse/AAP-33572>

## Description

Sentiment feedback (ThumbsUp/Down) UI implementation

### Steps to test
1. Pull down the PR
2. Run unit tests

### Scenarios tested

(Unit tests will be provided soon...)

## Production deployment

- [X] This code change is ready for production on its own
- [ ] This code change requires the following considerations before going to production:

### CODE REVIEW

**Review by romartin — APPROVED** [review]

**Review by romartin — CHANGES_REQUESTED** [review]
As commented, please requesting also to update the call to the wisdom service's Feedback API accordingly.

Thanks @TamiTakamiya , great stuff ,we're close :D

**Comment by TamiTakamiya** [comment]
@romartin There were a few bugs in property names, etc. and I have fixed them. I ran this latest version with your service-side PR and verified that it could send a correct ChatFeedback request.  If you need a chatbot client for testing your code, please update the client code with this branch. Thanks!

**Comment by romartin** [comment]
Cool, thanks @TamiTakamiya , will do! 

BTW let me know once this is ready for review as well! anyway if any early issues found, will let u know too.

**Comment by romartin** [comment]
Hey @TamiTakamiya !

Tested against my PR https://github.com/ansible/ansible-ai-connect-service/pull/1413

The telemetry works well, so the request from the chatbot UI is successful :+1: 

On the other hand, once clicking on the thumbs up/down icons, although it sends the feedback, the **icon is NOT changing the "clicked" style** that let the user know that it has been clicked, and the feedback properly sent. Same way, after clicking, the icon clicked style should be preserved for that prompt/response.

Just once fixing this small UI thing, I think we are good to go. Thanks!

**Comment by TamiTakamiya** [comment]
> Hey @TamiTakamiya !
> 
> Tested against my PR #1413
> 
> The telemetry works well, so the request from the chatbot UI is successful 👍
> 
> On the other hand, once clicking on the thumbs up/down icons, although it sends the feedback, the **icon is NOT changing the "clicked" style** that let the user know that it has been clicked, and the feedback properly sent. Same way, after clicking, the icon clicked style should be preserved for that prompt/response.
> 
> Just once fixing this small UI thing, I think we are good to go. Thanks!

 I spent an hour on this and tried to find a way to implement this, but could not find a handy way... It is not a small UI thing.... (at least for me :-)
 
These icons are implemented as buttons, not links, by PatternFly chatbot widget.  So it does not remember whether it was visited or not. It is possible to specify additional CSS class name to each action (see attached image), but they need to be controlled by ourselves.  

image

I have opened [AAP-36568](https://issues.redhat.com/browse/AAP-36568) for that work and want to implement it using that separated ticket.  If it is ok, would you approve this PR? Thanks!

**Review by jameswnl — APPROVED** [review]

**Comment by TamiTakamiya** [comment]
@jameswnl @romartin I have update the code and integrated the additional GitHub feedback logic when a user clicked the ThumbsDown button.  The new code will change the background of clicked icon and once either ThumbsUp or ThumbDown is clicked, both of them for a specifc bot response are disabled.

https://github.com/user-attachments/assets/9ab05eff-185b-4e58-b254-5f3094e3cca3

Would you take a look at those changes again? Thanks!

**Review by jameswnl — APPROVED** [review]
Looks great!

**Comment by TamiTakamiya** [comment]
> As commented, please requesting also to update the call to the wisdom service's Feedback API accordingly.
> 
> Thanks @TamiTakamiya , great stuff ,we're close :D
@romartin  I believe those requested API changes are included. Pls review this again. Thanksl.

**Review by romartin — APPROVED** [review]

**Pull request merged**
