### PR TITLE
Update openAPI Schema for /me/summary endpoint

### PR DESCRIPTION
**Pull request by SiddharthRajaraman**
Updating openAPI Schema for:
Jira Issue: <https://issues.redhat.com/browse/AAP-26574>

## Description

As a new endpoint is being added, a new serializer must be created as well. This PR creates a new serializer which parses the html content from the /me/markdown endpoint
### Steps to test
1. Pull down the PR
2. Run the service
3. Access localhost:8000/api/v0/me/markdown and ensure content appears
4. Access s[waggerUI](http://localhost:8000/api/schema/swagger-ui/#/me/me_summary_retrieve) and validate example schema

## Production deployment

- [ ] This code change is ready for production on its own
- [ ] This code change requires the following considerations before going to production:

### CODE REVIEW

**Comment by goneri** [comment]
I suspect you need to run `make update-openapi-schema` after a change like this.

**Review by TamiTakamiya — DISMISSED** [review]
LGTM

**Comment by SiddharthRajaraman** [comment]
> I suspect you need to run `make update-openapi-schema` after a change like this.

@goneri I believe I did

**Review by TamiTakamiya — DISMISSED** [review]
LGTM. Thanks!

**Comment by TamiTakamiya** [comment]
Hmmm.... Code looks good, but unit tests are failing... Why?

**Comment by SiddharthRajaraman** [comment]
@TamiTakamiya I'm not sure.. not only are the tests failing but when testing extension using the service running from this branch, it also fails

**Comment by TamiTakamiya** [comment]
@SiddharthRajaraman It was much more complicated than I thought. Sorry for having approved this without paying much attension to UT failures.

It looks like we need to move the logic to convert a user object to markdown from view.py to serializer.py, which makes sense because a serializer should serialize an object to a serialized form.  Pls take a look at #1220, which I prototyped for this. Thanks!

**Comment by goneri** [comment]
Honestly, I don't understand what this is for. But it sounds strange. The `serializer_class` attribute, is to set a class to load the endpoint parameters, here we don't have any parameter. So it should just be find.

**Review by TamiTakamiya — APPROVED** [review]

**Pull request merged**
